config/routes.rb
Rails.application.routes.draw do
  root 'page#top'
  get 'page/info'
  get 'page/contact'

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  resources :users, shallow: true do
    resources :addresses
    resources :wish_lists
    resources :books, except: [:edit]
  end

  resources :books do
    resources :wishes, only: [:show, :create]
    resources :book_addresses, only: [:create]
    resources :evals, only: [:create]
  end

  resources :wishes, only: [:update, :destroy], shallow: true do
    resources :replies, only: [:create, :update, :destroy]
  end

  resources :items, only: [:index]
  resources :trades, only: [:show]
end

app/views/shared/_footer.html.erb
<footer id="footer" class="clearfix">
  <div class="footer">
    <div class="container">
      <div class="footer-inner">
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <p class="text-center logo-font"><strong>© <%= Time.now.year %> <%= app_title %></strong></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="header fixed clearfix">
  	<div class="header-left clearfix">
  		<div id="logo" class="logo">
  			<h2 class="page-title text-center logo-font"><%= app_title %></h2>
  		</div>
  	</div>
  	<div class="header-right clearfix">
    	<div class="main-navigation animated">
    		<nav class="navbar navbar-default" role="navigation">
            <ul class="nav navbar-nav">
              <li><%= link_to items_path do %><i class="fa fa-globe fa-2x pr-10"></i><% end %></li>
              <% if user_signed_in? %>
                <li><%= link_to user_path(current_user) do %><i class="fa fa-user-o fa-2x pr-10"></i><% end %></li>
                <li><%= link_to destroy_user_session_path, method: :delete do %><i class="fa fa-sign-out fa-2x pr-10"></i><% end %></li>
              <% end %>
            </ul>
    		</nav>
    	</div>
    </div>
</header>

app/views/shared/_header_old.html.erb
<div class="header-container">
  <div class="header-top dark">
    <div class="container">
      <div class="row">
        <div class="col-xs-3 col-sm-6 col-md-3">
          <% if user_signed_in? %>
            <button type="button" class="navbar-toggle offcanvas-toggle" data-toggle="offcanvas" data-target="#js-bootstrap-offcanvas">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
          <% end %>
        </div>
        <div class="col-xs-9 col-sm-6 col-md-9">
          <div id="header-top-second" class="clearfix">
            <div class="header-top-dropdown text-right">
              <% if user_signed_in? %>
                <%= link_to destroy_user_session_path, method: :delete, class: "btn dropdown-toggle btn-default btn-sm" do %><i class="fa fa-unlock-alt pr-10"></i> ログアウト<% end %>
              <% else %>
                <div class="btn-group">
                <%= link_to new_user_registration_path, class:"btn btn-default btn-sm" do %><i class="fa fa-user pr-10"></i> 新規登録<% end %>
                <%= link_to new_user_session_path, class: "btn btn-default btn-sm" do %><i class="fa fa-lock pr-10"></i> ログイン<% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<nav class="navbar navbar-offcanvas" role="navigation" id="js-bootstrap-offcanvas">
  <ul class="list-group">
    <% if user_signed_in? %>
      <div class="user-info">
        <% animal = Animal.find(current_user.icon).name %>
        <%= image_tag(icon(animal), class: "#{icon_style(animal)}") %>
        <span><%= current_user.username %></span>
      </div>
    <% end %>
    <br>
    <%= active_link_to user_path(current_user), :active => [['users'], ['show']], class: 'list-group-item' do %><i class="fa fa-home pr-10"></i> ホーム<% end %>
    <%= active_link_to deals_path, class: "list-group-item" do %><i class="fa fa-gavel pr-10"></i> 現在の取引<% end %>
    <%= active_link_to new_user_book_path(current_user), class: "list-group-item" do %><i class="fa fa-plus pr-10"></i> 本の登録<% end %>
    <%= active_link_to user_books_path(current_user), :active => [['books'], ['index']], class: 'list-group-item' do %><i class="fa fa-book pr-10"></i> マイブック<% end %>
    <%= active_link_to user_negotiates_path(current_user), class: 'list-group-item' do %><i class="fa fa-handshake-o pr-10"></i> 交渉している取引<% end %>
    <%= active_link_to edit_user_path(current_user), class: 'list-group-item' do %><i class="fa fa-user-circle-o pr-10"></i> プロフィールの編集<% end %>
    <hr>
    <%= active_link_to page_info_path, class: 'list-group-item' do %><i class="fa fa-info-circle pr-10"></i> <span class="logo-font"><%= app_title %>の使い方</span><% end %>
    <%= active_link_to page_contact_path(current_user), class: 'list-group-item' do %><i class="fa fa-commenting pr-10"></i> フィードバック<% end %>
	</ul>
  <hr>
  <p class="logo-font sidebar-logo"><strong>© <%= Time.now.year %> <%= app_title %></strong></p>
</nav>

app/views/shared/_status_form.html.erb
<%= form_for(object) do |f| %>
  <%= f.hidden_field :status, value: num %>
  <%= f.submit "取引に出す", class: "btn btn-gray btn-sm" %>
<% end %>