config/routes.rb
Rails.application.routes.draw do
  root 'page#top'
  get 'page/info'
  get 'page/contact'

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  resources :users, shallow: true do
    resources :addresses
    resources :wish_lists
    resources :books, except: [:edit]
  end

  resources :books do
    resources :wishes, only: [:show, :create]
    resources :book_addresses, only: [:create]
    resources :evals, only: [:create]
  end

  resources :wishes, only: [:update, :destroy], shallow: true do
    resources :replies, only: [:create, :update, :destroy]
  end

  resources :items, only: [:index]
  resources :trades, only: [:show]
end

app/views/page/info.html.erb
<div class="info-content section">
  <div class="row">
  	<div class="col-md-4">
  		<h5 class="text-center logo-font">1.本を登録する</h5>
  		<div class="separator"></div>
      <p>あなたの持っている本の中で、誰かと交換してみたいものを登録してください.</p>
      <p><strong>本の登録は簡単にできます.</strong></p>
      <p>タイトル,著者名あるいはISBNコードを入力するだけです.</p>
  	</div>
    <div class="col-md-2">
      <%= image_tag('info1') %>
    </div>
		<div class="col-md-4">
      <h5 class="text-center logo-font">2.取引に出す</h5>
  		<div class="separator"></div>
      <p>あなたが登録した本を取引に出します.</p>
      <p>本を取引に出すと,他のユーザがあなたの本に交渉することができます.</p>
      <p><strong>もちろん,他のユーザがすでに取引に出した本にあなたが交渉することもできます.</strong></p>
      <p>ただし,取引に出した本は交渉に使うことができませんし,交渉に出した本は取引に出すこともできません.</p>
      <p><strong>また交渉を取り消すことはできますが,取引に出した本は1週間は取引に出たままとなります.</strong></p>
		</div>
    <div class="col-md-2">
      <%= image_tag('info2') %>
    </div>
  </div>
</div>
<div class="info-content section">
	<div class="row">
		<div class="col-md-4">
      <h5 class="text-center logo-font">3.取引の成立</h5>
  		<div class="separator"></div>
      <p>あなたが取引に出した本が他のユーザから交渉された場合,その交渉の中からあなたは取引を成立させたい本を選択することができます.</p>
      <p>もしあなたが取引を成立させるボタンを押した場合,その時点でユーザ同士の本の交換が決定します.</p>
      <p><strong>つまり,逆にあなたが交渉に出した本については,取引主があなたの本との取引を成立させた場合,即座にあなたとの本の交換が決まります.</strong></p>
      <p class="info-danger"><strong>また取引は1週間が期限となりますので,あなたの取引が多くのユーザから交渉されていたとしてもあなたが1週間取引を成立させなかった場合,その取引はキャンセルされます.</strong></p>
		</div>
    <div class="col-md-2">
      <%= image_tag('info3') %>
    </div>
    <div class="col-md-4">
      <h5 class="text-center logo-font">4.本の交換</h5>
      <div class="separator"></div>
      <p>あなたの取引あるいは交渉が成立した場合,ユーザ同士で本の交換を行っていただきます.</p>
      <p class="info-danger"><strong>本の交換時には,あなたの住所を相手方に通知する必要がありますので,その点については事前にご了承をいただいた上で,<span class="logo-font"><%= app_title %></span>をご利用いただきますようお願い致します.</strong></p>
      <p>また本の交換は交換ページの手順通りにしていただければ,交換を行っていただけるようになっております.</p>
      <p><strong>簡易的に本の交換ができるよう,ユーザ同士のメッセージ機能等はご用意しておりません.</strong></p>
      <p>本の交換は常識を持って行っていただきますようお願い致します.</p>
      <p>交換中に何か問題が発生しました場合は,お問い合わせフォームから報告をお願い致します.</p>
    </div>
    <div class="col-md-2">
      <%= image_tag('info4') %>
    </div>
	</div>
</div>

app/views/page/top.html.erb
<div class="container pv-40">
	<div class="row">
		<div class="col-md-8 text-center col-md-offset-2 pv-40">
			<div class="object-non-visible pv-40 animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="100">
				<h1 class="page-title text-center logo-font"><%= app_title %></h1>
				<div class="separator"></div>
				<h3 class="text-center"><em>読み終わった本を交換しよう</em></h3>
			</div>
      <%= link_to new_registration_path(resource_name), class: 'btn btn-animated btn-lg btn-primary' do %>今すぐ始める <i class="fa fa-arrow-right"></i><% end %>
	</div>
</div>