config/routes.rb
Rails.application.routes.draw do
  root 'page#top'
  get 'page/info'
  get 'page/contact'

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  resources :users, shallow: true do
    resources :addresses
    resources :wish_lists
    resources :books, except: [:edit]
  end

  resources :books do
    resources :wishes, only: [:show, :create]
    resources :book_addresses, only: [:create]
    resources :evals, only: [:create]
  end

  resources :wishes, only: [:update, :destroy], shallow: true do
    resources :replies, only: [:create, :update, :destroy]
  end

  resources :items, only: [:index]
  resources :trades, only: [:show]
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :user_check, :user_book_check

  def index
    @items = Book.where(status: 0).where.not(user_id: current_user)
    @search = @items.search(params[:q])
    @search_items = @search.result(distinct: true)
    @wish = current_user.wishes.build
  end
end

app/views/items/_links.html.erb
<% if current_user.already_negotiate?(object) %>
  <%= link_to "やっぱりいらない", negotiate_path(current_user.children.find_by(parent_id: object.id)), class: "btn btn-danger btn-sm", method: :delete,
    data: { confirm: 'ほしいな！を取り消してもよろしいですか？' } %>
<% elsif current_user.books.where(status: 0).blank? %>
  <div class="alert alert-danger small-font">
    交換できる本を持っていません
  </div>
<% elsif current_user.until_negotiate?(object) %>
  <%= render 'actions/form' %>
<% end %>

app/views/items/_search.html.erb
<%= search_form_for(search, url: items_path, method: :get) do |f| %>
  <%= f.search_field :title_or_author_cont, placeholder: 'タイトルあるいは著者名で検索できます', class: 'form-control' %>
<% end %>

app/views/items/index.html.erb
<%= render 'search', search: @search if @items.any? %>
<% @items.each do |item| %>
  <div class="listing-item mb-20 book-image">
    <div class="col-md-4 col-sm-6 col-xs-6 item-detail">
      <div class="elements-list clearfix">
        <% if current_user.already_reject_wish(item) %>
          <div class="alert alert-danger text-center">お断りされました</div>
        <% elsif wish = current_user.already_wish(item) %>
          <% if reply = wish.replies.find_by(status: 0) %>
            <%= render 'shared/modal/reply_modal', wish: wish, reply: reply %>
            <button class="btn btn-info btn-sm" data-toggle="modal" data-target="#replyModal">お返しをもらっています</button>
          <% elsif wish.replies.find_by(status: 2) %>
            <%= link_to '本の交換が決まりました！', trade_path(item.trade), class: 'btn btn-info btn-sm' %>
          <% elsif wish.replies.find_by(status: 1) %>
            <div class="alert alert-success text-center">これがいいな！を断りました</div>
          <% else %>
            <%= link_to 'ほしいな！を取り消す', wish_path(wish), method: :delete, data: { confirm: '本当に削除してもよろしいですか？' }, class: 'btn btn-danger btn-sm' %>
          <% end %>
        <% else %>
          <%= render 'shared/modal/wish_list_modal', item: item %>
          <%= render 'wishes/form/create_form', item: item %>
        <% end %>
      </div>
      <div class="overlay-container">
        <% if item.image.blank? %>
          <%= image_tag('no-image.png') %>
          <div class="book-info">
            <p class="title"><%= item.title.truncate(15) %></p>
            <p class="author"><%= item.author.truncate(15) %></p>
          </div>
        <% else %>
          <%= image_tag(item.image) %>
        <% end %>
        <div class="set-top">
          <% animal = Animal.find(item.user.icon).name %>
          <%= image_tag(icon(animal), class: "#{icon_style(animal)}", align: "middle") if current_user.not_mine?(item) %>
        </div>
        <% unless current_user.already_wish(item) %>
          <div class="set-bottom">
            <button class="btn btn-info btn-sm" data-toggle="modal" data-target="#wish-listModal">このユーザの<br>ほしいものリスト</button>
          </div>
        <% end %>
        <p class="bg-warning p-20">
          <small><strong><%= item.condition_i18n %></strong></small>
        </p>
      </div>
    </div>
  </div>
<% end %>